"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def get_sum():
    limit = 4 * (10 ** 6) # 4 billion
    fibo_sequence = [1, 2] # from problem
    num = 0 # stores the next number of the sequence
    summatory = 2 # starts with the first even-valued term

    while True:
        num = fibo_sequence[-1] + fibo_sequence[-2]
        if num > limit:
            break
        if num % 2 == 0:
            summatory += num
        fibo_sequence.append(num)

    return summatory

print(get_sum())